# Importação das Bibliotecas

In [2]:
import os
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [3]:
# baixa o dataset do KaggleHub e retorna o caminho local onde os arquivos foram armazenados
root = kagglehub.dataset_download("maxhorowitz/nflplaybyplay2009to2016") 
print("Root:", root)

Root: C:\Users\Lapa\.cache\kagglehub\datasets\maxhorowitz\nflplaybyplay2009to2016\versions\6

In [4]:
for dirpath, dirnames, filenames in os.walk(root):  # percorre recursivamente todas as pastas dentro do diretório root
    for f in filenames:  # itera sobre cada arquivo encontrado em cada pasta
        print(os.path.relpath(os.path.join(dirpath, f), root))  # imprime o caminho relativo de cada arquivo em relação ao diretório root

NFL Play by Play 2009-2016 (v3).csv
NFL Play by Play 2009-2017 (v4) PROCESSED.parquet
NFL Play by Play 2009-2017 (v4).csv
NFL Play by Play 2009-2018 (v5).csv

In [5]:
# Exemplo: ajuste para o arquivo real que você viu no os.walk
csv_path = os.path.join(root, "NFL Play by Play 2009-2017 (v4).csv") # cria o caminho completo para o arquivo CSV dentro do diretório root

df = pd.read_csv(csv_path) # lê o arquivo CSV e carrega os dados em um DataFrame do pandas
df.head()

C:\Users\Lapa\AppData\Local\Temp\ipykernel_7608\848581222.py:4: DtypeWarning: Columns (0: DefTwoPoint, 1: BlockingPlayer) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path) # lê o arquivo CSV e carrega os dados em um DataFrame do pandas

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

# Dicionário dos dados

| Nº | Coluna | Descrição | Tipo de dado |
|---|---|---|---|
| 0 | Date | Data em que o jogo foi realizado | Date |
| 1 | GameID | Identificador único do jogo | Int |
| 2 | Drive | Número da campanha (drive) ofensiva dentro do jogo | Int |
| 3 | qtr | Quarto do jogo em que a jogada ocorreu (1 a 4 e prorrogação) | Categórico (5 tipos) |
| 4 | down | Tentativa (down) da jogada (1 a 4) | Categórico (4 tipos) |
| 5 | time | Tempo restante no quarto, no formato mm:ss | String |
| 6 | TimeUnder | Minutos restantes no quarto/metade do jogo | Int |
| 7 | TimeSecs | Segundos restantes até o fim da metade do jogo | Float |
| 8 | PlayTimeDiff | Tempo decorrido entre a jogada anterior e a atual, em segundos | Float |
| 9 | SideofField | Time em cujo lado do campo a bola está posicionada | Categórico (37 tipos) |
| 10 | yrdln | Jardas até a linha de gol, contadas a partir da linha do campo (1 a 50) | Float |
| 11 | yrdline100 | Distância da bola até a end zone adversária (1 a 99 jardas) | Float |
| 12 | ydstogo | Jardas que faltam para conquistar o first down | Int |
| 13 | ydsnet | Jardas líquidas ganhas pela campanha até o momento | Int |
| 14 | GoalToGo | Indica se a situação é goal to go (jardas restantes até a end zone) | Boolean |
| 15 | FirstDown | Indica se a jogada resultou em first down | Boolean |
| 16 | posteam | Time que está com a posse de bola (ataque) | Categórico (35 tipos) |
| 17 | DefensiveTeam | Time que está na defesa | Categórico (35 tipos) |
| 18 | desc | Descrição textual detalhada da jogada | String |
| 19 | PlayAttempted | Indica se uma jogada foi tentada (sempre 1) | Boolean |
| 20 | Yards.Gained | Jardas ganhas (ou perdidas, se negativo) na jogada | Int |
| 21 | sp | Indica se a jogada foi pontuadora (scoring play) | Boolean |
| 22 | Touchdown | Indica se a jogada resultou em touchdown | Boolean |
| 23 | ExPointResult | Resultado do ponto extra (convertido, perdido, bloqueado, abortado) | Categórico (4 tipos) |
| 24 | TwoPointConv | Resultado da tentativa de conversão de 2 pontos (sucesso ou falha) | Categórico (2 tipos) |
| 25 | DefTwoPoint | Resultado de conversão de 2 pontos pela defesa | Categórico (2 tipos) |
| 26 | Safety | Indica se a jogada resultou em safety | Boolean |
| 27 | Onsidekick | Indica se foi um chute curto (onside kick) | Boolean |
| 28 | PuntResult | Resultado do punt (limpo ou bloqueado) | Categórico (2 tipos) |
| 29 | PlayType | Tipo da jogada (passe, corrida, punt, field goal, kickoff etc.) | Categórico (15 tipos) |
| 30 | Passer | Nome do passador (quarterback) | String |
| 31 | Passer_ID | Identificador do passador | String |
| 32 | PassAttempt | Indica se houve tentativa de passe | Boolean |
| 33 | PassOutcome | Resultado do passe (completo ou incompleto) | Categórico (2 tipos) |
| 34 | PassLength | Tamanho do passe (curto ou longo) | Categórico (3 tipos) |
| 35 | AirYards | Jardas percorridas pela bola no ar | Int |
| 36 | YardsAfterCatch | Jardas ganhas pelo recebedor após a recepção | Int |
| 37 | QBHit | Indica se o quarterback foi atingido na jogada | Boolean |
| 38 | PassLocation | Região do campo para onde o passe foi direcionado (esquerda, meio, direita) | Categórico (3 tipos) |
| 39 | InterceptionThrown | Indica se o passe foi interceptado | Boolean |
| 40 | Interceptor | Nome do jogador que interceptou o passe | String |
| 41 | Rusher | Nome do jogador que correu com a bola | String |
| 42 | Rusher_ID | Identificador do corredor | String |
| 43 | RushAttempt | Indica se houve tentativa de corrida | Boolean |
| 44 | RunLocation | Região do campo em que a corrida ocorreu (esquerda, meio, direita) | Categórico (3 tipos) |
| 45 | RunGap | Espaço da linha ofensiva por onde a corrida passou (end, guard, tackle) | Categórico (3 tipos) |
| 46 | Receiver | Nome do recebedor do passe | String |
| 47 | Receiver_ID | Identificador do recebedor | String |
| 48 | Reception | Indica se houve recepção completa | Boolean |
| 49 | ReturnResult | Resultado do retorno (de punt ou kickoff) | Categórico (3 tipos) |
| 50 | Returner | Nome do jogador que fez o retorno | String |
| 51 | BlockingPlayer | Nome do jogador que bloqueou o chute | String |
| 52 | Tackler1 | Nome do primeiro jogador que realizou o tackle | String |
| 53 | Tackler2 | Nome do segundo jogador que realizou o tackle | String |
| 54 | FieldGoalResult | Resultado do field goal (convertido, errado, bloqueado) | Categórico (3 tipos) |
| 55 | FieldGoalDistance | Distância do field goal em jardas | Float |
| 56 | Fumble | Indica se houve fumble (bola solta) | Boolean |
| 57 | RecFumbTeam | Time que recuperou o fumble | Categórico (34 tipos) |
| 58 | RecFumbPlayer | Jogador que recuperou o fumble | String |
| 59 | Sack | Indica se houve sack no quarterback | Boolean |
| 60 | Challenge.Replay | Indica se houve desafio (challenge) ou revisão por replay | Boolean |
| 61 | ChalReplayResult | Resultado do desafio (mantida ou revertida) | Categórico (2 tipos) |
| 62 | Accepted.Penalty | Indica se uma penalidade foi aceita | Boolean |
| 63 | PenalizedTeam | Time penalizado | Categórico (34 tipos) |
| 64 | PenaltyType | Tipo da penalidade | Categórico (77 tipos) |
| 65 | PenalizedPlayer | Nome do jogador penalizado | String |
| 66 | Penalty.Yards | Jardas da penalidade | Int |
| 67 | PosTeamScore | Pontuação do time com a posse de bola | Int |
| 68 | DefTeamScore | Pontuação do time na defesa | Int |
| 69 | ScoreDiff | Diferença de placar (time com a posse menos time na defesa) | Int |
| 70 | AbsScoreDiff | Diferença absoluta de placar | Int |
| 71 | HomeTeam | Time mandante | Categórico (35 tipos) |
| 72 | AwayTeam | Time visitante | Categórico (35 tipos) |
| 73 | Timeout_Indicator | Indica se houve pedido de tempo (timeout) | Boolean |
| 74 | Timeout_Team | Time que pediu o timeout | Categórico (35 tipos) |
| 75 | posteam_timeouts_pre | Timeouts restantes do time com a posse antes da jogada | Int |
| 76 | HomeTimeouts_Remaining_Pre | Timeouts restantes do mandante antes da jogada | Int |
| 77 | AwayTimeouts_Remaining_Pre | Timeouts restantes do visitante antes da jogada | Int |
| 78 | HomeTimeouts_Remaining_Post | Timeouts restantes do mandante após a jogada | Int |
| 79 | AwayTimeouts_Remaining_Post | Timeouts restantes do visitante após a jogada | Int |
| 80 | No_Score_Prob | Probabilidade de nenhuma pontuação até o fim da campanha | Float |
| 81 | Opp_Field_Goal_Prob | Probabilidade de o adversário fazer um field goal | Float |
| 82 | Opp_Safety_Prob | Probabilidade de o adversário fazer um safety | Float |
| 83 | Opp_Touchdown_Prob | Probabilidade de o adversário fazer um touchdown | Float |
| 84 | Field_Goal_Prob | Probabilidade de o time com a posse fazer um field goal | Float |
| 85 | Safety_Prob | Probabilidade de o time com a posse sofrer um safety | Float |
| 86 | Touchdown_Prob | Probabilidade de o time com a posse fazer um touchdown | Float |
| 87 | ExPoint_Prob | Probabilidade de conversão do ponto extra | Float |
| 88 | TwoPoint_Prob | Probabilidade de conversão de 2 pontos | Float |
| 89 | ExpPts | Pontos esperados (Expected Points) antes da jogada | Float |
| 90 | EPA | Expected Points Added: variação dos pontos esperados causada pela jogada | Float |
| 91 | airEPA | EPA atribuído à parte aérea do passe (jardas no ar) | Float |
| 92 | yacEPA | EPA atribuído às jardas após a recepção | Float |
| 93 | Home_WP_pre | Probabilidade de vitória do mandante antes da jogada | Float |
| 94 | Away_WP_pre | Probabilidade de vitória do visitante antes da jogada | Float |
| 95 | Home_WP_post | Probabilidade de vitória do mandante após a jogada | Float |
| 96 | Away_WP_post | Probabilidade de vitória do visitante após a jogada | Float |
| 97 | Win_Prob | Probabilidade de vitória do time com a posse de bola | Float |
| 98 | WPA | Win Probability Added: variação da probabilidade de vitória causada pela jogada | Float |
| 99 | airWPA | WPA atribuído à parte aérea do passe | Float |
| 100 | yacWPA | WPA atribuído às jardas após a recepção | Float |
| 101 | Season | Temporada (ano) a que o jogo pertence | Int |

# Analisando Banco de Dados Coletado

In [6]:
df.info(verbose = True)

<class 'pandas.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Data columns (total 102 columns):
 #    Column                       Dtype
---   ------                       -----
 0    Date                         str
 1    GameID                       int64
 2    Drive                        int64
 3    qtr                          int64
 4    down                         float64
 5    time                         str
 6    TimeUnder                    int64
 7    TimeSecs                     float64
 8    PlayTimeDiff                 float64
 9    SideofField                  str
 10   yrdln                        float64
 11   yrdline100                   float64
 12   ydstogo                      int64
 13   ydsnet                       int64
 14   GoalToGo                     float64
 15   FirstDown                    float64
 16   posteam                      str
 17   DefensiveTeam                str
 18   desc                         str
 19   PlayAttempted                int64
 20   Yards.Gained                 int64
 21   sp                           int64
 22   Touchdown                    int64
 23   ExPointResult                str
 24   TwoPointConv                 str
 25   DefTwoPoint                  str
 26   Safety                       int64
 27   Onsidekick                   int64
 28   PuntResult                   str
 29   PlayType                     str
 30   Passer                       str
 31   Passer_ID                    str
 32   PassAttempt                  int64
 33   PassOutcome                  str
 34   PassLength                   str
 35   AirYards                     int64
 36   YardsAfterCatch              int64
 37   QBHit                        int64
 38   PassLocation                 str
 39   InterceptionThrown           int64
 40   Interceptor                  str
 41   Rusher                       str
 42   Rusher_ID                    str
 43   RushAttempt                  int64
 44   RunLocation                  str
 45   RunGap                       str
 46   Receiver                     str
 47   Receiver_ID                  str
 48   Reception                    int64
 49   ReturnResult                 str
 50   Returner                     str
 51   BlockingPlayer               str
 52   Tackler1                     str
 53   Tackler2                     str
 54   FieldGoalResult              str
 55   FieldGoalDistance            float64
 56   Fumble                       int64
 57   RecFumbTeam                  str
 58   RecFumbPlayer                str
 59   Sack                         int64
 60   Challenge.Replay             int64
 61   ChalReplayResult             str
 62   Accepted.Penalty             int64
 63   PenalizedTeam                str
 64   PenaltyType                  str
 65   PenalizedPlayer              str
 66   Penalty.Yards                int64
 67   PosTeamScore                 float64
 68   DefTeamScore                 float64
 69   ScoreDiff                    float64
 70   AbsScoreDiff                 float64
 71   HomeTeam                     str
 72   AwayTeam                     str
 73   Timeout_Indicator            int64
 74   Timeout_Team                 str
 75   posteam_timeouts_pre         int64
 76   HomeTimeouts_Remaining_Pre   int64
 77   AwayTimeouts_Remaining_Pre   int64
 78   HomeTimeouts_Remaining_Post  int64
 79   AwayTimeouts_Remaining_Post  int64
 80   No_Score_Prob                float64
 81   Opp_Field_Goal_Prob          float64
 82   Opp_Safety_Prob              float64
 83   Opp_Touchdown_Prob           float64
 84   Field_Goal_Prob              float64
 85   Safety_Prob                  float64
 86   Touchdown_Prob               float64
 87   ExPoint_Prob                 float64
 88   TwoPoint_Prob                float64
 89   ExpPts                       float64
 90   EPA                          float64
 91   airEPA                       float64
 92   yacEPA                       float64
 93   Home_WP_pre                  float64
 94   Away_WP_pre                  float64
 95   Home_WP_post                 float64
 96   Away_WP_post                 float64
 97   Win_Prob                     float64
 98   WPA                          float64
 99   airWPA                       float64
 100  yacWPA                       float64
 101  Season                       int64
dtypes: float64(33), int64(31), str(38)
memory usage: 380.5 MB

In [7]:
df.shape

(407688, 102)

In [8]:
for coluna in df.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df[coluna])}")
    print(f"Valores únicos: {df[coluna].nunique()}")
    print(f"Valores nulos: {df[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df[coluna].dtypes}")
    print('-------------------------')
    
print("Linhas inteiras duplicadas:", df.duplicated().sum())

Coluna: Date
Quantidade de valores: 407688
Valores únicos: 426
Valores nulos: 0
Valores duplicados: 407262
Tipo dos dados: str
-------------------------
Coluna: GameID
Quantidade de valores: 407688
Valores únicos: 2304
Valores nulos: 0
Valores duplicados: 405384
Tipo dos dados: int64
-------------------------
Coluna: Drive
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 0
Valores duplicados: 407653
Tipo dos dados: int64
-------------------------
Coluna: qtr
Quantidade de valores: 407688
Valores únicos: 5
Valores nulos: 0
Valores duplicados: 407683
Tipo dos dados: int64
-------------------------
Coluna: down
Quantidade de valores: 407688
Valores únicos: 4
Valores nulos: 61154
Valores duplicados: 407683
Tipo dos dados: float64
-------------------------
Coluna: time
Quantidade de valores: 407688

Valores únicos: 901
Valores nulos: 224
Valores duplicados: 406786
Tipo dos dados: str
-------------------------
Coluna: TimeUnder
Quantidade de valores: 407688
Valores únicos: 16
Valores nulos: 0
Valores duplicados: 407672
Tipo dos dados: int64
-------------------------
Coluna: TimeSecs
Quantidade de valores: 407688
Valores únicos: 4369
Valores nulos: 224
Valores duplicados: 403318
Tipo dos dados: float64
-------------------------
Coluna: PlayTimeDiff
Quantidade de valores: 407688
Valores únicos: 157
Valores nulos: 444
Valores duplicados: 407530
Tipo dos dados: float64
-------------------------
Coluna: SideofField
Quantidade de valores: 407688
Valores únicos: 37
Valores nulos: 528
Valores duplicados: 407650
Tipo dos dados: str
-------------------------
Coluna: yrdln
Quantidade de valores: 407688
Valores únicos: 50
Valores nulos: 840
Valores duplicados: 407637
Tipo dos dados: float64
-------------------------
Coluna: yrdline100
Quantidade de valores: 407688
Valores únicos: 99
Valores nulos: 840
Valores duplicados: 407588
Tipo dos dados: float64
-------------------------
Coluna: ydstogo
Quantidade de valores: 407688
Valores únicos: 47
Valores nulos: 0
Valores duplicados: 407641
Tipo dos dados: int64
-------------------------
Coluna: ydsnet
Quantidade de valores: 407688
Valores únicos: 154
Valores nulos: 0
Valores duplicados: 407534
Tipo dos dados: int64
-------------------------
Coluna: GoalToGo
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 840
Valores duplicados: 407685
Tipo dos dados: float64
-------------------------
Coluna: FirstDown
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 28811
Valores duplicados: 407685
Tipo dos dados: float64
-------------------------
Coluna: posteam
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 24992
Valores duplicados: 407652
Tipo dos dados: str
-------------------------
Coluna: DefensiveTeam
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 24992
Valores duplicados: 407652
Tipo dos dados: str
-------------------------
Coluna: desc
Quantidade de valores: 407688
Valores únicos: 375962
Valores nulos: 2
Valores duplicados: 31725
Tipo dos dados: str
-------------------------
Coluna: PlayAttempted
Quantidade de valores: 407688
Valores únicos: 1
Valores nulos: 0
Valores duplicados: 407687
Tipo dos dados: int64
-------------------------
Coluna: Yards.Gained
Quantidade de valores: 407688
Valores únicos: 127
Valores nulos: 0
Valores duplicados: 407561
Tipo dos dados: int64
-------------------------
Coluna: sp
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: Touchdown
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: ExPointResult
Quantidade de valores: 407688
Valores únicos: 4
Valores nulos: 397578
Valores duplicados: 407683
Tipo dos dados: str
-------------------------
Coluna: TwoPointConv
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 407083
Valores duplicados: 407685
Tipo dos dados: str
-------------------------
Coluna: DefTwoPoint
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 407664
Valores duplicados: 407685
Tipo dos dados: str
-------------------------
Coluna: Safety
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: Onsidekick
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: PuntResult
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 385317
Valores duplicados: 407685
Tipo dos dados: str
-------------------------
Coluna: PlayType
Quantidade de valores: 407688
Valores únicos: 15
Valores nulos: 0
Valores duplicados: 407673
Tipo dos dados: str
-------------------------
Coluna: Passer
Quantidade de valores: 407688
Valores únicos: 352
Valores nulos: 240045
Valores duplicados: 407335
Tipo dos dados: str
-------------------------
Coluna: Passer_ID
Quantidade de valores: 407688
Valores únicos: 334
Valores nulos: 237445
Valores duplicados: 407353
Tipo dos dados: str
-------------------------
Coluna: PassAttempt
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: PassOutcome
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 239506
Valores duplicados: 407685
Tipo dos dados: str
-------------------------
Coluna: PassLength
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 240520
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: AirYards
Quantidade de valores: 407688
Valores únicos: 109
Valores nulos: 0
Valores duplicados: 407579
Tipo dos dados: int64
-------------------------
Coluna: YardsAfterCatch
Quantidade de valores: 407688
Valores únicos: 115
Valores nulos: 0
Valores duplicados: 407573
Tipo dos dados: int64
-------------------------
Coluna: QBHit
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: PassLocation
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 240520
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: InterceptionThrown
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: Interceptor
Quantidade de valores: 407688
Valores únicos: 898
Valores nulos: 403168
Valores duplicados: 406789
Tipo dos dados: str
-------------------------
Coluna: Rusher
Quantidade de valores: 407688
Valores únicos: 1231
Valores nulos: 287124
Valores duplicados: 406456
Tipo dos dados: str
-------------------------
Coluna: Rusher_ID
Quantidade de valores: 407688
Valores únicos: 1070
Valores nulos: 283654
Valores duplicados: 406617
Tipo dos dados: str
-------------------------
Coluna: RushAttempt
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: RunLocation
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 288178
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: RunGap
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 320260
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: Receiver
Quantidade de valores: 407688
Valores únicos: 1386
Valores nulos: 246127
Valores duplicados: 406301
Tipo dos dados: str
-------------------------
Coluna: Receiver_ID
Quantidade de valores: 407688
Valores únicos: 1488
Valores nulos: 250328
Valores duplicados: 406199
Tipo dos dados: str
-------------------------
Coluna: Reception
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: ReturnResult
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 389450
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: Returner
Quantidade de valores: 407688
Valores únicos: 1082
Valores nulos: 382384
Valores duplicados: 406605
Tipo dos dados: str
-------------------------
Coluna: BlockingPlayer
Quantidade de valores: 407688
Valores únicos: 101
Valores nulos: 407571
Valores duplicados: 407586
Tipo dos dados: str
-------------------------
Coluna: Tackler1
Quantidade de valores: 407688
Valores únicos: 3636
Valores nulos: 166134
Valores duplicados: 404051
Tipo dos dados: str
-------------------------
Coluna: Tackler2
Quantidade de valores: 407688
Valores únicos: 2456
Valores nulos: 357953
Valores duplicados: 405231
Tipo dos dados: str
-------------------------
Coluna: FieldGoalResult
Quantidade de valores: 407688
Valores únicos: 3
Valores nulos: 398629
Valores duplicados: 407684
Tipo dos dados: str
-------------------------
Coluna: FieldGoalDistance
Quantidade de valores: 407688
Valores únicos: 52
Valores nulos: 398740
Valores duplicados: 407635
Tipo dos dados: float64
-------------------------
Coluna: Fumble
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: RecFumbTeam
Quantidade de valores: 407688
Valores únicos: 34
Valores nulos: 403315
Valores duplicados: 407653
Tipo dos dados: str
-------------------------
Coluna: RecFumbPlayer
Quantidade de valores: 407688
Valores únicos: 1827
Valores nulos: 403315
Valores duplicados: 405860
Tipo dos dados: str
-------------------------
Coluna: Sack
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: Challenge.Replay
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: ChalReplayResult
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 404286
Valores duplicados: 407685
Tipo dos dados: str
-------------------------
Coluna: Accepted.Penalty
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: PenalizedTeam
Quantidade de valores: 407688
Valores únicos: 34
Valores nulos: 378189
Valores duplicados: 407653
Tipo dos dados: str
-------------------------
Coluna: PenaltyType
Quantidade de valores: 407688
Valores únicos: 77
Valores nulos: 391261
Valores duplicados: 407610
Tipo dos dados: str
-------------------------
Coluna: PenalizedPlayer
Quantidade de valores: 407688
Valores únicos: 3357
Valores nulos: 379403
Valores duplicados: 404330
Tipo dos dados: str
-------------------------
Coluna: Penalty.Yards
Quantidade de valores: 407688
Valores únicos: 59
Valores nulos: 0
Valores duplicados: 407629
Tipo dos dados: int64
-------------------------
Coluna: PosTeamScore
Quantidade de valores: 407688
Valores únicos: 61
Valores nulos: 26904
Valores duplicados: 407626
Tipo dos dados: float64
-------------------------
Coluna: DefTeamScore
Quantidade de valores: 407688
Valores únicos: 60
Valores nulos: 26904
Valores duplicados: 407627
Tipo dos dados: float64
-------------------------
Coluna: ScoreDiff
Quantidade de valores: 407688
Valores únicos: 108
Valores nulos: 24988
Valores duplicados: 407579
Tipo dos dados: float64
-------------------------
Coluna: AbsScoreDiff
Quantidade de valores: 407688
Valores únicos: 57
Valores nulos: 26904
Valores duplicados: 407630
Tipo dos dados: float64
-------------------------
Coluna: HomeTeam
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 0
Valores duplicados: 407653
Tipo dos dados: str
-------------------------
Coluna: AwayTeam
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 0
Valores duplicados: 407653
Tipo dos dados: str
-------------------------
Coluna: Timeout_Indicator
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: int64
-------------------------
Coluna: Timeout_Team
Quantidade de valores: 407688
Valores únicos: 35
Valores nulos: 390885
Valores duplicados: 407652
Tipo dos dados: str
-------------------------
Coluna: posteam_timeouts_pre
Quantidade de valores: 407688
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 407684
Tipo dos dados: int64
-------------------------
Coluna: HomeTimeouts_Remaining_Pre
Quantidade de valores: 407688
Valores únicos: 7
Valores nulos: 0
Valores duplicados: 407681
Tipo dos dados: int64
-------------------------
Coluna: AwayTimeouts_Remaining_Pre
Quantidade de valores: 407688
Valores únicos: 5
Valores nulos: 0
Valores duplicados: 407683
Tipo dos dados: int64
-------------------------
Coluna: HomeTimeouts_Remaining_Post
Quantidade de valores: 407688
Valores únicos: 7
Valores nulos: 0
Valores duplicados: 407681
Tipo dos dados: int64
-------------------------
Coluna: AwayTimeouts_Remaining_Post
Quantidade de valores: 407688
Valores únicos: 5
Valores nulos: 0
Valores duplicados: 407683
Tipo dos dados: int64
-------------------------
Coluna: No_Score_Prob
Quantidade de valores: 407688
Valores únicos: 281307
Valores nulos: 176
Valores duplicados: 126380
Tipo dos dados: float64
-------------------------
Coluna: Opp_Field_Goal_Prob
Quantidade de valores: 407688
Valores únicos: 281306
Valores nulos: 176
Valores duplicados: 126381
Tipo dos dados: float64
-------------------------
Coluna: Opp_Safety_Prob
Quantidade de valores: 407688
Valores únicos: 281306
Valores nulos: 176
Valores duplicados: 126381
Tipo dos dados: float64
-------------------------
Coluna: Opp_Touchdown_Prob
Quantidade de valores: 407688
Valores únicos: 281306
Valores nulos: 176
Valores duplicados: 126381
Tipo dos dados: float64
-------------------------
Coluna: Field_Goal_Prob
Quantidade de valores: 407688
Valores únicos: 281357
Valores nulos: 176
Valores duplicados: 126330
Tipo dos dados: float64
-------------------------
Coluna: Safety_Prob
Quantidade de valores: 407688
Valores únicos: 281306
Valores nulos: 176
Valores duplicados: 126381
Tipo dos dados: float64
-------------------------
Coluna: Touchdown_Prob
Quantidade de valores: 407688
Valores únicos: 281306
Valores nulos: 176
Valores duplicados: 126381
Tipo dos dados: float64
-------------------------
Coluna: ExPoint_Prob
Quantidade de valores: 407688
Valores únicos: 11
Valores nulos: 0
Valores duplicados: 407677
Tipo dos dados: float64
-------------------------
Coluna: TwoPoint_Prob
Quantidade de valores: 407688
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 407686
Tipo dos dados: float64
-------------------------
Coluna: ExpPts
Quantidade de valores: 407688
Valores únicos: 281368
Valores nulos: 176
Valores duplicados: 126319
Tipo dos dados: float64
-------------------------
Coluna: EPA
Quantidade de valores: 407688
Valores únicos: 351090
Valores nulos: 369
Valores duplicados: 56597
Tipo dos dados: float64
-------------------------
Coluna: airEPA
Quantidade de valores: 407688
Valores únicos: 156924
Valores nulos: 248394
Valores duplicados: 250763
Tipo dos dados: float64
-------------------------
Coluna: yacEPA
Quantidade de valores: 407688
Valores únicos: 135186
Valores nulos: 248498
Valores duplicados: 272501
Tipo dos dados: float64
-------------------------
Coluna: Home_WP_pre
Quantidade de valores: 407688
Valores únicos: 362561
Valores nulos: 24954
Valores duplicados: 45126
Tipo dos dados: float64
-------------------------
Coluna: Away_WP_pre
Quantidade de valores: 407688
Valores únicos: 362562
Valores nulos: 24954
Valores duplicados: 45125
Tipo dos dados: float64
-------------------------
Coluna: Home_WP_post
Quantidade de valores: 407688
Valores únicos: 363190
Valores nulos: 26587
Valores duplicados: 44497
Tipo dos dados: float64
-------------------------
Coluna: Away_WP_post
Quantidade de valores: 407688
Valores únicos: 363360
Valores nulos: 26587
Valores duplicados: 44327
Tipo dos dados: float64
-------------------------
Coluna: Win_Prob
Quantidade de valores: 407688
Valores únicos: 360389
Valores nulos: 25009
Valores duplicados: 47298
Tipo dos dados: float64
-------------------------
Coluna: WPA
Quantidade de valores: 407688
Valores únicos: 366549
Valores nulos: 5541
Valores duplicados: 41138
Tipo dos dados: float64
-------------------------
Coluna: airWPA
Quantidade de valores: 407688
Valores únicos: 158705
Valores nulos: 248501
Valores duplicados: 248982
Tipo dos dados: float64
-------------------------
Coluna: yacWPA
Quantidade de valores: 407688
Valores únicos: 135470
Valores nulos: 248762
Valores duplicados: 272217
Tipo dos dados: float64
-------------------------
Coluna: Season
Quantidade de valores: 407688
Valores únicos: 9
Valores nulos: 0
Valores duplicados: 407679
Tipo dos dados: int64
-------------------------
Linhas inteiras duplicadas: 0

In [9]:
df.dtypes.value_counts()

str        38
float64    33
int64      31
Name: count, dtype: int64

# Tratamento DType Warnings
Colunas 25 e 51 estão com tipos mistos

In [10]:
colunas_problema = df.columns[[25, 51]]
colunas_problema

Index(['DefTwoPoint', 'BlockingPlayer'], dtype='str')

## Verificando DefTwoPoints

In [11]:
df[colunas_problema[0]].apply(type).value_counts()

DefTwoPoint
<class 'float'>    407664
<class 'str'>          24
Name: count, dtype: int64

In [12]:
df.loc[df[colunas_problema[0]].apply(type) == str, colunas_problema[0]].head()

278907    Failure
284977    Failure
286715    Failure
301227    Failure
304879    Success
Name: DefTwoPoint, dtype: str

In [13]:
df.loc[df[colunas_problema[0]].apply(type) == float, colunas_problema[0]].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: DefTwoPoint, dtype: str

In [14]:
df[colunas_problema[0]].unique()

<ArrowStringArray>
[nan, 'Failure', 'Success']
Length: 3, dtype: str

In [15]:
print(df[colunas_problema[0]].isna().sum())

407664

In [16]:
df[colunas_problema[0]] = df[colunas_problema[0]].astype("category")

## Verificando BlockingPlayer

In [17]:
df[colunas_problema[1]].apply(type).value_counts()

BlockingPlayer
<class 'float'>    407571
<class 'str'>         117
Name: count, dtype: int64

In [18]:
df.loc[df[colunas_problema[1]].apply(type) == str, colunas_problema[1]].head()

1425       J.McGraw
2779     B.Williams
16313      J.Hester
21255       G.Hayes
27429       E.Smith
Name: BlockingPlayer, dtype: str

In [19]:
df.loc[df[colunas_problema[1]].apply(type) == float, colunas_problema[1]].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: BlockingPlayer, dtype: str

In [20]:
df[colunas_problema[1]].unique()

<ArrowStringArray>
[             nan,       'J.McGraw',     'B.Williams',       'J.Hester',
        'G.Hayes',        'E.Smith',        'C.Lynch',        'G.Hardy',
     'R.Jennings',        'D.Curry',
 ...
     'C.Reynolds',   'T.Matakevich',    'C.Littleton',       'J.Willis',
       'J.Hardee',     'R.Burkhead',      'S.Barrett',       'M.Thomas',
 'K.Grugier-Hill',       'A.Walker']
Length: 102, dtype: str

In [21]:
print(df[colunas_problema[0]].isna().sum())

407664

In [22]:
df[colunas_problema[1]] = df[colunas_problema[1]].astype("string")

# Tratamento dos Tipos de Dados Coluna por Coluna

In [23]:
df.dtypes.value_counts()

str         36
float64     33
int64       31
category     1
string       1
Name: count, dtype: int64

In [24]:
missing_tokens = ["NA", "N/A", "null", "None", "nan", "UNKNOWN"]

df.isin(missing_tokens).sum()

Date        0
GameID      0
Drive       0
qtr         0
down        0
           ..
Win_Prob    0
WPA         0
airWPA      0
yacWPA      0
Season      0
Length: 102, dtype: int64

In [25]:
data_dict_object = pd.DataFrame({  # cria um DataFrame resumo (dicionário de dados) apenas para colunas do tipo object

    "variavel": df.columns,  # adiciona uma coluna com os nomes das variáveis do tipo object

    "Amostras (em ordem alfabética)": [", ".join(sorted(df[col].dropna().astype(str).unique()))  # lista os valores únicos da coluna, ordenados alfabeticamente e separados por vírgula
                                       if df[col].notna().any() else None  # se a coluna tiver apenas NaN, retorna None
                                       for col in df.columns],  # repete esse processo para cada coluna object

    "Amostras (em ordem de frequência)": [", ".join(df[col].dropna().astype(str).value_counts().index.tolist())  # lista os valores únicos ordenados pela frequência (mais comum primeiro)
                                          if df[col].notna().any() else None  # se só tiver NaN, retorna None
                                          for col in df.columns],  # repete para cada coluna object
    
    "qtd_valores_unicos": [df[col].nunique()  # calcula a quantidade de valores únicos em cada coluna
                           for col in df.columns]

})

# Colocar em ordem alfabética
data_dict_object = data_dict_object.sort_values(
    by="Amostras (em ordem alfabética)",  # ordena o DataFrame com base nos valores das amostras em ordem alfabética
    ascending=True,  # ordem crescente
    na_position="last"  # coloca os valores None no final
).reset_index(drop=True)  # reseta o índice após a ordenação

data_dict_object  # exibe o DataFrame final com o resumo das colunas do tipo object

,variavel,Amostras (em ordem alfabética),Amostras (em ordem de frequência),qtd_valores_unicos
0,desc,D.Carr was injured during the play. His retur...,"Two-Minute Warning, END GAME, END QUARTER 3, E...",375962
1,yacWPA,"-0.00010012757616417732, -0.000100340302382359...","0.0, -0.0251957783479736, -0.0252632266577083,...",135470
2,airWPA,"-0.00010029350816576076, -0.000100417486330945...","0.0027938013996506, -0.0222869972404158, -0.04...",158705
3,WPA,"-0.0001003243160555912, -0.0001003961838429434...","0.0, 0.0003402928156365226, -0.022469425258057...",366549
4,yacEPA,"-0.00010066025684274392, -0.000101204823163669...","0.0, -7.0, -0.3235258536112761, -0.86449107304...",135186
...,...,...,...,...
97,ReturnResult,"Fair Catch, Touchback, Touchdown","Touchback, Fair Catch, Touchdown",3
98,ChalReplayResult,"Reversed, Upheld","Upheld, Reversed",2
99,RunGap,"end, guard, tackle","end, tackle, guard",3
100,PassLocation,"left, middle, right","right, left, middle",3
101,RunLocation,"left, middle, right","right, left, middle",3

## Date - Transformação no tipo datetime64

In [26]:
df['Date'].isna().sum()

np.int64(0)

In [27]:
df["Date"].nunique()

426

In [28]:
df['Date'] = df['Date'].astype("datetime64[ns]")

In [29]:
df['Date'].head()

0   2009-09-10
1   2009-09-10
2   2009-09-10
3   2009-09-10
4   2009-09-10
Name: Date, dtype: datetime64[ns]

# Categóricos

In [30]:
acronyms = ['HomeTeam','Timeout_Team','AwayTeam','posteam','DefensiveTeam','RecFumbTeam','PenalizedTeam','SideofField']
# SideofField possui uma categoria diferente (50), possivelmente é um erro
df[acronyms] = df[acronyms].astype("category")

In [31]:
object_cols = df.select_dtypes(include="object").columns.tolist()
print('Número restante de variáveis do tipo Object:',len(object_cols))

Número restante de variáveis do tipo Object: 27

C:\Users\Lapa\AppData\Local\Temp\ipykernel_7608\270096898.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns.tolist()

In [32]:
unique = ['PassLength','ExPointResult','PuntResult','FieldGoalResult','PenaltyType','PassOutcome','PlayType',
          'TwoPointConv','ReturnResult','ChalReplayResult','RunGap','RunLocation','PassLocation']
df[unique] = df[unique].astype("category")

In [33]:
object_cols = df.select_dtypes(include="object").columns.tolist()
print('Número restante de variáveis do tipo Object:',len(object_cols))

Número restante de variáveis do tipo Object: 14

C:\Users\Lapa\AppData\Local\Temp\ipykernel_7608\270096898.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns.tolist()

# Strings

In [34]:
names = ['Rusher','Tackler1','Receiver','Returner','PenalizedPlayer','Tackler2','RecFumbPlayer','Interceptor','Passer', 'Rusher_ID','Receiver_ID','Passer_ID', 'desc']
df[names] = df[names].astype("string")

In [35]:
object_cols = df.select_dtypes(include="object").columns.tolist()
print('Número restante de variáveis do tipo Object:',len(object_cols))

Número restante de variáveis do tipo Object: 1

C:\Users\Lapa\AppData\Local\Temp\ipykernel_7608\270096898.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns.tolist()

## Horário do jogo

In [36]:
df["time"] = pd.to_timedelta("00:" + df["time"].astype(str), errors="coerce")

In [37]:
df['time'].head()

0   0 days 00:15:00
1   0 days 00:14:53
2   0 days 00:14:16
3   0 days 00:13:35
4   0 days 00:13:27
Name: time, dtype: timedelta64[us]

# Verificando colunas

In [38]:
df.dtypes.value_counts()

float64            33
int64              31
string             14
category            5
category            2
category            2
category            2
datetime64[ns]      1
timedelta64[us]     1
category            1
category            1
category            1
category            1
category            1
category            1
category            1
category            1
category            1
category            1
category            1
Name: count, dtype: int64

In [39]:
df.dtypes.map(lambda t: t.name).value_counts()

float64            33
int64              31
category           22
string             14
datetime64[ns]      1
timedelta64[us]     1
Name: count, dtype: int64

# Criando Parquet

In [40]:
df.to_parquet("tipos_tratados.parquet", index=False)

# Lendo Parquet

In [43]:
df = pd.read_parquet("./tipos_tratados.parquet")

# Visão geral do DataFrame

In [45]:
df.head(10)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,0 days 00:15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,0 days 00:14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,0 days 00:14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,0 days 00:13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,0 days 00:13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009
5,2009-09-10,2009091000,2,1,1.0,0 days 00:13:16,14,3496.0,11.0,TEN,...,NaN,0.558929,0.441071,0.578453,0.421547,0.441071,-0.019524,NaN,NaN,2009
6,2009-09-10,2009091000,2,1,2.0,0 days 00:12:40,13,3460.0,36.0,TEN,...,0.163935,0.578453,0.421547,0.582881,0.417119,0.421547,-0.004427,-0.010456,0.006029,2009
7,2009-09-10,2009091000,2,1,3.0,0 days 00:12:11,13,3431.0,29.0,TEN,...,NaN,0.582881,0.417119,0.617544,0.382456,0.417119,-0.034663,NaN,NaN,2009
8,2009-09-10,2009091000,2,1,4.0,0 days 00:11:34,12,3394.0,37.0,TEN,...,NaN,0.617544,0.382456,0.591489,0.408511,0.382456,0.026054,NaN,NaN,2009
9,2009-09-10,2009091000,3,1,1.0,0 days 00:11:24,12,3384.0,10.0,TEN,...,0.541602,0.591489,0.408511,0.585405,0.414595,0.591489,-0.006084,-0.024526,0.018442,2009

In [46]:
df.shape

(407688, 102)

In [47]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Data columns (total 102 columns):
 #    Column                       Dtype
---   ------                       -----
 0    Date                         datetime64[ns]
 1    GameID                       int64
 2    Drive                        int64
 3    qtr                          int64
 4    down                         float64
 5    time                         timedelta64[us]
 6    TimeUnder                    int64
 7    TimeSecs                     float64
 8    PlayTimeDiff                 float64
 9    SideofField                  category
 10   yrdln                        float64
 11   yrdline100                   float64
 12   ydstogo                      int64
 13   ydsnet                       int64
 14   GoalToGo                     float64
 15   FirstDown                    float64
 16   posteam                      category
 17   DefensiveTeam                category
 18   desc                         string
 19   PlayAttempted                int64
 20   Yards.Gained                 int64
 21   sp                           int64
 22   Touchdown                    int64
 23   ExPointResult                category
 24   TwoPointConv                 category
 25   DefTwoPoint                  category
 26   Safety                       int64
 27   Onsidekick                   int64
 28   PuntResult                   category
 29   PlayType                     category
 30   Passer                       string
 31   Passer_ID                    string
 32   PassAttempt                  int64
 33   PassOutcome                  category
 34   PassLength                   category
 35   AirYards                     int64
 36   YardsAfterCatch              int64
 37   QBHit                        int64
 38   PassLocation                 category
 39   InterceptionThrown           int64
 40   Interceptor                  string
 41   Rusher                       string
 42   Rusher_ID                    string
 43   RushAttempt                  int64
 44   RunLocation                  category
 45   RunGap                       category
 46   Receiver                     string
 47   Receiver_ID                  string
 48   Reception                    int64
 49   ReturnResult                 category
 50   Returner                     string
 51   BlockingPlayer               string
 52   Tackler1                     string
 53   Tackler2                     string
 54   FieldGoalResult              category
 55   FieldGoalDistance            float64
 56   Fumble                       int64
 57   RecFumbTeam                  category
 58   RecFumbPlayer                string
 59   Sack                         int64
 60   Challenge.Replay             int64
 61   ChalReplayResult             category
 62   Accepted.Penalty             int64
 63   PenalizedTeam                category
 64   PenaltyType                  category
 65   PenalizedPlayer              string
 66   Penalty.Yards                int64
 67   PosTeamScore                 float64
 68   DefTeamScore                 float64
 69   ScoreDiff                    float64
 70   AbsScoreDiff                 float64
 71   HomeTeam                     category
 72   AwayTeam                     category
 73   Timeout_Indicator            int64
 74   Timeout_Team                 category
 75   posteam_timeouts_pre         int64
 76   HomeTimeouts_Remaining_Pre   int64
 77   AwayTimeouts_Remaining_Pre   int64
 78   HomeTimeouts_Remaining_Post  int64
 79   AwayTimeouts_Remaining_Post  int64
 80   No_Score_Prob                float64
 81   Opp_Field_Goal_Prob          float64
 82   Opp_Safety_Prob              float64
 83   Opp_Touchdown_Prob           float64
 84   Field_Goal_Prob              float64
 85   Safety_Prob                  float64
 86   Touchdown_Prob               float64
 87   ExPoint_Prob                 float64
 88   TwoPoint_Prob                float64
 89   ExpPts                       float64
 90   EPA                          float64
 91   airEPA                       float64
 92   yacEPA                       float64
 93   Home_WP_pre                  float64
 94   Away_WP_pre                  float64
 95   Home_WP_post                 float64
 96   Away_WP_post                 float64
 97   Win_Prob                     float64
 98   WPA                          float64
 99   airWPA                       float64
 100  yacWPA                       float64
 101  Season                       int64
dtypes: category(22), datetime64[ns](1), float64(33), int64(31), string(14), timedelta64[us](1)
memory usage: 301.8 MB

# Avaliando valores ausentes

Total de valores ausentes por coluna

In [48]:
pd.set_option('display.max_rows', None)  # Mostra todas as linhas
missing = df.isna().sum().sort_values(ascending=False)
missing

DefTwoPoint                    407664
BlockingPlayer                 407571
TwoPointConv                   407083
ChalReplayResult               404286
RecFumbPlayer                  403315
RecFumbTeam                    403315
Interceptor                    403168
FieldGoalDistance              398740
FieldGoalResult                398629
ExPointResult                  397578
PenaltyType                    391261
Timeout_Team                   390885
ReturnResult                   389450
PuntResult                     385317
Returner                       382384
PenalizedPlayer                379403
PenalizedTeam                  378189
Tackler2                       357953
RunGap                         320260
RunLocation                    288178
Rusher                         287124
Rusher_ID                      283654
Receiver_ID                    250328
yacWPA                         248762
airWPA                         248501
yacEPA                         248498
airEPA                         248394
Receiver                       246127
PassLength                     240520
PassLocation                   240520
Passer                         240045
PassOutcome                    239506
Passer_ID                      237445
Tackler1                       166134
down                            61154
FirstDown                       28811
DefTeamScore                    26904
AbsScoreDiff                    26904
PosTeamScore                    26904
Home_WP_post                    26587
Away_WP_post                    26587
Win_Prob                        25009
posteam                         24992
DefensiveTeam                   24992
ScoreDiff                       24988
Home_WP_pre                     24954
Away_WP_pre                     24954
WPA                              5541
yrdline100                        840
GoalToGo                          840
yrdln                             840
SideofField                       528
PlayTimeDiff                      444
EPA                               369
TimeSecs                          224
time                              224
Opp_Touchdown_Prob                176
No_Score_Prob                     176
Opp_Field_Goal_Prob               176
Opp_Safety_Prob                   176
Safety_Prob                       176
Field_Goal_Prob                   176
Touchdown_Prob                    176
ExpPts                            176
desc                                2
Date                                0
GameID                              0
sp                                  0
qtr                                 0
Drive                               0
QBHit                               0
YardsAfterCatch                     0
AirYards                            0
PassAttempt                         0
Touchdown                           0
Safety                              0
Onsidekick                          0
PlayType                            0
ydsnet                              0
PlayAttempted                       0
TimeUnder                           0
ydstogo                             0
Yards.Gained                        0
InterceptionThrown                  0
RushAttempt                         0
Reception                           0
Penalty.Yards                       0
Accepted.Penalty                    0
Sack                                0
Challenge.Replay                    0
Fumble                              0
posteam_timeouts_pre                0
HomeTimeouts_Remaining_Pre          0
AwayTimeouts_Remaining_Pre          0
AwayTimeouts_Remaining_Post         0
HomeTimeouts_Remaining_Post         0
AwayTeam                            0
HomeTeam                            0
Timeout_Indicator                   0
TwoPoint_Prob                       0
ExPoint_Prob                        0
Season                              0
dtype: int64

Pegando os valores por porcentagem

In [49]:
missing_percent = df.isna().mean() * 100
missing_percent.sort_values(ascending=False)

DefTwoPoint                    99.994113
BlockingPlayer                 99.971302
TwoPointConv                   99.851602
ChalReplayResult               99.165538
RecFumbPlayer                  98.927366
RecFumbTeam                    98.927366
Interceptor                    98.891309
FieldGoalDistance              97.805184
FieldGoalResult                97.777958
ExPointResult                  97.520162
PenaltyType                    95.970693
Timeout_Team                   95.878466
ReturnResult                   95.526481
PuntResult                     94.512716
Returner                       93.793293
PenalizedPlayer                93.062097
PenalizedTeam                  92.764320
Tackler2                       87.800720
RunGap                         78.555170
RunLocation                    70.685917
Rusher                         70.427386
Rusher_ID                      69.576245
Receiver_ID                    61.401856
yacWPA                         61.017739
airWPA                         60.953720
yacEPA                         60.952984
airEPA                         60.927474
Receiver                       60.371411
PassLength                     58.996095
PassLocation                   58.996095
Passer                         58.879584
PassOutcome                    58.747375
Passer_ID                      58.241842
Tackler1                       40.750280
down                           15.000196
FirstDown                       7.066924
DefTeamScore                    6.599164
AbsScoreDiff                    6.599164
PosTeamScore                    6.599164
Home_WP_post                    6.521409
Away_WP_post                    6.521409
Win_Prob                        6.134348
posteam                         6.130178
DefensiveTeam                   6.130178
ScoreDiff                       6.129197
Home_WP_pre                     6.120857
Away_WP_pre                     6.120857
WPA                             1.359128
yrdline100                      0.206040
GoalToGo                        0.206040
yrdln                           0.206040
SideofField                     0.129511
PlayTimeDiff                    0.108907
EPA                             0.090510
TimeSecs                        0.054944
time                            0.054944
Opp_Touchdown_Prob              0.043170
No_Score_Prob                   0.043170
Opp_Field_Goal_Prob             0.043170
Opp_Safety_Prob                 0.043170
Safety_Prob                     0.043170
Field_Goal_Prob                 0.043170
Touchdown_Prob                  0.043170
ExpPts                          0.043170
desc                            0.000491
Date                            0.000000
GameID                          0.000000
sp                              0.000000
qtr                             0.000000
Drive                           0.000000
QBHit                           0.000000
YardsAfterCatch                 0.000000
AirYards                        0.000000
PassAttempt                     0.000000
Touchdown                       0.000000
Safety                          0.000000
Onsidekick                      0.000000
PlayType                        0.000000
ydsnet                          0.000000
PlayAttempted                   0.000000
TimeUnder                       0.000000
ydstogo                         0.000000
Yards.Gained                    0.000000
InterceptionThrown              0.000000
RushAttempt                     0.000000
Reception                       0.000000
Penalty.Yards                   0.000000
Accepted.Penalty                0.000000
Sack                            0.000000
Challenge.Replay                0.000000
Fumble                          0.000000
posteam_timeouts_pre            0.000000
HomeTimeouts_Remaining_Pre      0.000000
AwayTimeouts_Remaining_Pre      0.000000
AwayTimeouts_Remaining_Post     0.000000
HomeTimeouts_Remaining_Post     0.000000
AwayTeam                        0.000000
HomeTeam                        0.000000
Timeout_Indicator               0.000000
TwoPoint_Prob                   0.000000
ExPoint_Prob                    0.000000
Season                          0.000000
dtype: float64

#### Identificar colunas com mais de 50% de valores ausentes

In [53]:
missing_50 = missing_percent[missing_percent >= 50].index
missing_50

Index(['ExPointResult', 'TwoPointConv', 'DefTwoPoint', 'PuntResult', 'Passer',
       'Passer_ID', 'PassOutcome', 'PassLength', 'PassLocation', 'Interceptor',
       'Rusher', 'Rusher_ID', 'RunLocation', 'RunGap', 'Receiver',
       'Receiver_ID', 'ReturnResult', 'Returner', 'BlockingPlayer', 'Tackler2',
       'FieldGoalResult', 'FieldGoalDistance', 'RecFumbTeam', 'RecFumbPlayer',
       'ChalReplayResult', 'PenalizedTeam', 'PenaltyType', 'PenalizedPlayer',
       'Timeout_Team', 'airEPA', 'yacEPA', 'airWPA', 'yacWPA'],
      dtype='str')

#### Identificar colunas entre 30% e 50% de valores ausentes

In [55]:
# Identificar colunas com mais de 50% de missing
missing_30_50 = missing_percent[missing_percent.between(30, 50, inclusive='right')].index
missing_30_50

Index(['Tackler1'], dtype='str')

#### Identificar colunas entre 20% e 30% de valores ausentes

In [58]:
missing_20_30 = missing_percent[missing_percent.between(20, 30, inclusive='right')].index
missing_20_30

Index([], dtype='str')

#### Identificar colunas entre 10% e 20% de valores ausentes

In [59]:
missing_10_20 = missing_percent[missing_percent.between(10, 20, inclusive='right')].index
missing_10_20

Index(['down'], dtype='str')

#### Identificar colunas entre 5% e 10% de valores ausentes

In [60]:
missing_5_10 = missing_percent[missing_percent.between(5, 10, inclusive='right')].index
missing_5_10

Index(['FirstDown', 'posteam', 'DefensiveTeam', 'PosTeamScore', 'DefTeamScore',
       'ScoreDiff', 'AbsScoreDiff', 'Home_WP_pre', 'Away_WP_pre',
       'Home_WP_post', 'Away_WP_post', 'Win_Prob'],
      dtype='str')

#### Identificar colunas com menos de 5% de valores ausentes

In [62]:
missing_5 = missing_percent[missing_percent.between(0, 5, inclusive='right')].index
missing_5

Index(['time', 'TimeSecs', 'PlayTimeDiff', 'SideofField', 'yrdln',
       'yrdline100', 'GoalToGo', 'desc', 'No_Score_Prob',
       'Opp_Field_Goal_Prob', 'Opp_Safety_Prob', 'Opp_Touchdown_Prob',
       'Field_Goal_Prob', 'Safety_Prob', 'Touchdown_Prob', 'ExpPts', 'EPA',
       'WPA'],
      dtype='str')

# Tratando colunas com mais de 50% de valores ausentes

# Tratando colunas entre 30% e 50% de valores ausentes

# Tratando colunas entre 20% e 30% de valores ausentes

# Tratando colunas entre 10% e 20% de valores ausentes

# Tratando colunas entre 5% e 10% de valores ausentes

# Tratando colunas com menos de 5% de valores ausentes