## Desafio D — Sistema de Registro de Preços

### Problema

Quais características diferenciam contratações realizadas com e sem Sistema de Registro de Preços?

### Possíveis perguntas

- O SRP é mais frequente em determinados tipos de contratação?
- Existem diferenças nos valores das contratações?
- Determinados órgãos utilizam SRP proporcionalmente mais do que outros?

### Variável de interesse

Quando disponível:

```text
srp
```

### Possíveis análises

- proporções;
- tabelas cruzadas;
- comparação de valores;
- teste qui-quadrado.


documentação API: https://dadosabertos.compras.gov.br/swagger-ui/index.html

In [1]:
#!pip install requests pandas matplotlib -q

In [2]:
import requests
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
BASE_URL = "https://dadosabertos.compras.gov.br"

ENDPOINT_CONTRATACOES = "/modulo-contratacoes/1_consultarContratacoes_PNCP_14133"

url = BASE_URL + ENDPOINT_CONTRATACOES

print(url)

https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133

In [4]:
params = {
    "pagina": 1,
    "tamanhoPagina": 50,
    "dataPublicacaoPncpInicial": "2025-05-01",
    "dataPublicacaoPncpFinal": "2025-05-15",
    "codigoModalidade": 5
}

params

{'pagina': 1,
 'tamanhoPagina': 50,
 'dataPublicacaoPncpInicial': '2025-05-01',
 'dataPublicacaoPncpFinal': '2025-05-15',
 'codigoModalidade': 5}

In [5]:
resposta = requests.get(
    url,
    params=params,
    timeout=60
)

print("Status HTTP:", resposta.status_code)
print("URL consultada:", resposta.url)

Status HTTP: 200
URL consultada: https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133?pagina=1&tamanhoPagina=50&dataPublicacaoPncpInicial=2025-05-01&dataPublicacaoPncpFinal=2025-05-15&codigoModalidade=5

In [6]:
dados = resposta.json()

In [ ]:
def extrair_registros(json_resposta):
    if isinstance(json_resposta, list):
        return json_resposta

    if not isinstance(json_resposta, dict):
        return []

    for chave in ["resultado", "resultados", "data", "content"]:
        if chave in json_resposta and isinstance(json_resposta[chave], list):
            return json_resposta[chave]

    return []


registros = extrair_registros(dados)

print("Quantidade de registros encontrados:", len(registros))

Quantidade de registros encontrados: 50

In [18]:
print("JSON retornado:", registros)
df = pd.json_normalize(registros)
df.head

JSON retornado: [{'idCompra': '92648305900402025', 'numeroControlePNCP': '03643856000173-1-000032/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 32, 'orgaoEntidadeCnpj': '03643856000173', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 97067, 'orgaoEntidadeRazaoSocial': 'SERVICO SOCIAL DO COMERCIO - ADMINISTRACAO REGIONAL NO ESTADO DE MINAS GERAIS', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'N', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926483', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SERVICO SOCIAL DO COMERCIO - SESC AR/MG', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'MG', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'BELO HORIZONTE', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3106200, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90040', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92648305900402025', 'processo': '004001-07686', 'objetoCompra': 'Contratação de empresa especializada para serviços de fornecimento e instalação de piso esportivo na quadra poliesportiva do ginásio e piso esportivo sport out na quadra poliesportiva externa da unidade Sesc Uberaba, incluindo toda mão de obra, equipamentos ferramentas e insumos para perfeita realização dos serviços a ser medido por preço unitário na virtude do não detalhamento de projeto.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 179474.46, 'valorTotalHomologado': 134994.42, 'dataInclusaoPncp': '2025-05-02T07:15:29', 'dataAtualizacaoPncp': '2025-05-02T07:15:29', 'dataPublicacaoPncp': '2025-05-02T07:15:29', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-16T09:00:00', 'contratacaoExcluida': False}, {'idCompra': '51018005900032025', 'numeroControlePNCP': '29979036000140-1-000100/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 100, 'orgaoEntidadeCnpj': '29979036000140', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 26661, 'orgaoEntidadeRazaoSocial': 'INSTITUTO NACIONAL DO SEGURO SOCIAL', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'F', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '510180', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SUPERINTENDENCIA REGIONAL SUDESTE II', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'MG', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'BELO HORIZONTE', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3106200, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90003', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=51018005900032025', 'processo': '35014096253202481', 'objetoCompra': 'Contratação de serviços terceirizados nas áreas administrativas para os postos de Assistente Administrativo, Recepcionista, Ascensorista, Copeiro, Carregador e Encarregado, a serem executados com regime de dedicação exclusiva de mão de obra, em diversos setores e unidades vinculados à Superintendência Regional Sudeste II', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 0.0, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:34', 'dataAtualizacaoPncp': '2025-05-02T07:15:34', 'dataPublicacaoPncp': '2025-05-02T07:15:34', 'dataAberturaPropostaPncp': '2025-05-02T09:00:00', 'dataEncerramentoPropostaPncp': '2025-05-21T10:00:00', 'contratacaoExcluida': False}, {'idCompra': '93008805900012025', 'numeroControlePNCP': '19481436000178-1-000006/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 6, 'orgaoEntidadeCnpj': '19481436000178', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 72415, 'orgaoEntidadeRazaoSocial': 'AGENCIA ESTADUAL DE RECURSOS HIDRICOS - AGERH', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'E', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '930088', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'EES - AGENCIA ESTADUAL DE RECURSOS HIDRICOS', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'ES', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'VITÓRIA', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3205309, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90001', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=93008805900012025', 'processo': '2024-5ZHFJ', 'objetoCompra': 'Contratação de Serviço de Copeiragem, Conservação e Manutenção Predial com fornecimento de equipamentos e ferramentas.', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 4, 'situacaoCompraNomePncp': 'Suspensa', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 10131.09, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:38', 'dataAtualizacaoPncp': '2025-05-22T08:55:28', 'dataPublicacaoPncp': '2025-05-02T07:15:38', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-21T10:00:00', 'contratacaoExcluida': False}, {'idCompra': '92670305900802025', 'numeroControlePNCP': '26981455000129-1-000078/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 78, 'orgaoEntidadeCnpj': '26981455000129', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 23517, 'orgaoEntidadeRazaoSocial': 'AGENCIA MUNICIPAL DE REGULACAO DE SERVICOS DELEGADOS- ARSER', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926703', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'AG. DE LICIT., CONT. E CONV. DE MACEIO', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'AL', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'MACEIÓ', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2704302, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90080', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'Em caso de divergência existente entre as especificações do objeto descritas no cadastro do Sistema COMPRASNET e as especificações constantes deste Edital e seus anexos, prevalecerão estas últimas. Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92670305900802025', 'processo': '12500.037111/2025', 'objetoCompra': 'Registro preços fornecimento utensílios e produtos de limpeza e higienização I (frac PE 90020/2025).', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 1885845.73, 'valorTotalHomologado': 864056.09, 'dataInclusaoPncp': '2025-05-02T07:15:42', 'dataAtualizacaoPncp': '2025-05-02T07:15:42', 'dataPublicacaoPncp': '2025-05-02T07:15:42', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-16T09:00:00', 'contratacaoExcluida': False}, {'idCompra': '98013905900422025', 'numeroControlePNCP': '04034583000122-1-000041/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 41, 'orgaoEntidadeCnpj': '04034583000122', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 52383, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE RIO BRANCO', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '980139', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'CAC-PREFEITURA MUNICIPAL DE RIO BRANCO', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'AC', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'RIO BRANCO', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 1200401, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90042', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'Havendo qualquer divergência entre as especificações do sistema e as do edital, prevalecerão as últimas. Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=98013905900422025', 'processo': '001/2025', 'objetoCompra': 'Aquisição de material de consumo de água mineral em garrafão de 20L, Gelo em barra, Água mineral em garrafa pet contendo 500ml, Água em copos pet contendo 300ml, Garrafão plástico 20L retornável, Botijão para gás vazio de 13kg, Gás liquefeito acondicionada em botijão de 13kg mediante a sistema de troca de botija, para atender as necessidades da Secretaria Municipal de Finanças - SEFIN, no município de Rio Branco/AC.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 79607.2, 'valorTotalHomologado': 43476.2, 'dataInclusaoPncp': '2025-05-02T07:15:46', 'dataAtualizacaoPncp': '2025-05-02T07:15:46', 'dataPublicacaoPncp': '2025-05-02T07:15:46', 'dataAberturaPropostaPncp': '2025-05-05T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-15T10:00:00', 'contratacaoExcluida': False}, {'idCompra': '92682105900502025', 'numeroControlePNCP': '13927801000300-1-000057/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 57, 'orgaoEntidadeCnpj': '13927801000300', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 65662, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE SALVADOR', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926821', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SECRETARIA MUNICIPAL DE GESTÃO SALVADOR - BA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'BA', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'SALVADOR', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2927408, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90050', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'As especificações devem ser seguidas conforme o edital Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92682105900502025', 'processo': '14679/2025', 'objetoCompra': 'Aquisição de MATERIAL DE PESTICIDAS – (INSETICIDA, LARVICIDA E RATICIDA) que tem por finalidade, atender as necessidades do funcionalismo da Administração da Prefeitura Municipal do Salvador, visando manter o pleno funcionamento das atividades, no suporte das tarefas e ações operacionais, através do sistema de registro de preços.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 1125246.12, 'valorTotalHomologado': 70654.9, 'dataInclusaoPncp': '2025-05-02T07:15:50', 'dataAtualizacaoPncp': '2025-08-14T07:27:32', 'dataPublicacaoPncp': '2025-05-02T07:15:50', 'dataAberturaPropostaPncp': '2025-08-14T08:00:00', 'dataEncerramentoPropostaPncp': '2025-09-03T14:00:00', 'contratacaoExcluida': False}, {'idCompra': '92573405900182025', 'numeroControlePNCP': '27080555000147-1-000028/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 28, 'orgaoEntidadeCnpj': '27080555000147', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 24356, 'orgaoEntidadeRazaoSocial': 'SECRETARIA DE ESTADO DA AGRICULTURA, ABASTECIMENTO, AQUICULTURA E PESCA - SEAG', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'E', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '925734', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'EES-SECRET. EST. AGR. ABAST. AQUIC. E PESCA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'ES', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'VITÓRIA', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3205309, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90018', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92573405900182025', 'processo': '2024-2X4Q7', 'objetoCompra': 'Registro de Preços para Aquisição de Secador Cilindrico Rotativo para Secagem de Grãos de Café com Capacidade mínima de 6.400 Litros, conforme descrito no Aexo I do Edital.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 5185454.82, 'valorTotalHomologado': 5070000.0, 'dataInclusaoPncp': '2025-05-02T07:15:54', 'dataAtualizacaoPncp': '2025-05-02T07:15:54', 'dataPublicacaoPncp': '2025-05-02T07:15:54', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-15T10:00:00', 'contratacaoExcluida': False}, {'idCompra': '98340305900392025', 'numeroControlePNCP': '13811476000154-1-000108/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 108, 'orgaoEntidadeCnpj': '13811476000154', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 12165, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE CAETITE', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '983403', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'PREFEITURA MUNICIPAL DE CAETITE - BA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'BA', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'CAETITÉ', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2905206, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90039', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=98340305900392025', 'processo': '093/2025', 'objetoCompra': 'Registro de preços para futura e eventual aquisição de veículo utilitário, zero km, para atender as necessidades institucionais do Gabinete do Prefeito Municipal de Caetité-BA.', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 423000.0, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:57', 'dataAtualizacaoPncp': '2025-05-02T07:15:57', 'dataPublicacaoPncp': '2025-05-02T07:15:57', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-14T09:00:00', 'contratacaoExcluida': False}, {'idCompra': '92967905900012025', 'numeroControlePNCP': '48198725000162-1-000052/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 52, 'orgaoEntidadeCnpj': '48198725000162', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 83589, 'orgaoEntidadeRazaoSocial': 'CAMARA MUNICIPAL DE MOGI GUACU', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'L', 'orgaoSubrogadoPoderId': None, 'un

<bound method NDFrame.head of              idCompra            numeroControlePNCP  anoCompraPncp  \
0   92648305900402025  03643856000173-1-000032/2025           2025
1   51018005900032025  29979036000140-1-000100/2025           2025
2   93008805900012025  19481436000178-1-000006/2025           2025
3   92670305900802025  26981455000129-1-000078/2025           2025
4   98013905900422025  04034583000122-1-000041/2025           2025
5   92682105900502025  13927801000300-1-000057/2025           2025
6   92573405900182025  27080555000147-1-000028/2025           2025
7   98340305900392025  13811476000154-1-000108/2025           2025
8   92967905900012025  48198725000162-1-000052/2025           2025
9   98412305941422024  18715383000140-1-001258/2024           2024
10  98028605900072025  01612573000139-1-000013/2025           2025
11  98547705900152025  95589289000132-1-000038/2025           2025
12  09013305900682025  46374500000194-1-003439/2025           2025
13  45977605900102025  18239038000187-1-000011/2025           2025
14  98269105900152025  64487614000122-1-000075/2025           2025
15  18015805900142025  46377800000127-1-001783/2025           2025
16  98834305900652025  83102491000109-1-000093/2025           2025
17  53210105907532025  60747318000162-1-000718/2025           2025
18  13501205900212025  00348003000110-1-000119/2025           2025
19  98548705900242025  95583571000102-1-000060/2025           2025
20  98548705900252025  95583571000102-1-000061/2025           2025
21  53210105907542025  60747318000162-1-000719/2025           2025
22  93123205900242025  27080605001753-1-000073/2025           2025
23  18028705900012025  46377800000127-1-001784/2025           2025
24  98837505900212025  83009928000164-1-000023/2025           2025
25  92930405900042025  76416940000128-1-000134/2025           2025
26  98834305900662025  83102491000109-1-000094/2025           2025
27  93006705900032025  49226780000181-1-000012/2025           2025
28  98847705900232025  80869886000143-1-000026/2025           2025
29  98799505900302025  78103884000105-1-000090/2025           2025
30  92715505900152025  04371703000187-1-000001/2025           2025
31  98552105900132025  95640520000175-1-000015/2025           2025
32  92571505900052025  27080563000193-1-000021/2025           2025
33  92953605900012025  50544220000154-1-000054/2025           2025
34  09011605900512025  46374500000194-1-003440/2025           2025
35  98783705900372025  76205707000104-1-000056/2025           2025
36  98497505900192025  18133439000158-1-000034/2025           2025
37  98794905900202025  76416940000128-1-000135/2025           2025
38  93101905900152025  27080605000358-1-000023/2025           2025
39  45228605900242025  01266058000144-1-000063/2025           2025
40  92610705900062025  12517793000108-1-000023/2025           2025
41  92647305900072025  06272868000127-1-000011/2025           2025
42  98838305900522025  83009860000113-1-000097/2025           2025
43  38016805900042025  96291141000180-1-001836/2025           2025
44  98350105900352025  13937032000160-1-000741/2025           2025
45  38010805900052025  96291141000180-1-001837/2025           2025
46  98756505900422025  77816510000166-1-000091/2025           2025
47  45116405900462025  80257355000108-1-000082/2025           2025
48  09013305900692025  46374500000194-1-003441/2025           2025
49  98000505900052025  04092672000125-1-000022/2025           2025

    sequencialCompraPncp orgaoEntidadeCnpj orgaoSubrogadoCnpj  codigoOrgao  \
0                     32    03643856000173               None        97067
1                    100    29979036000140               None        26661
2                      6    19481436000178               None        72415
3                     78    26981455000129               None        23517
4                     41    04034583000122               None        52383
5                     57    13927801000300               None        65662
6                     28    27080555000147               None        24356
7                    108    13811476000154               None        12165
8                     52    48198725000162               None        83589
9                   1258    18715383000140               None        71432
10                    13    01612573000139               None        88898
11                    38    95589289000132               None        42352
12                  3439    46374500000194               None        34952
13                    11    18239038000187               None        95740
14                    75    64487614000122               None        38348
15                  1783    46377800000127               None        35311
16                    93    83102491000109               None        86035
17                   718    60747318000162               None        84184
18                   119    00348003000110               None        95145
19                    60    95583571000102               None        87060
20                    61    95583571000102               None        87060
21                   719    60747318000162               None        84184
22                    73    27080605001753               None        24382
23                  1784    46377800000127               None        35311
24                    23    83009928000164               None        85989
25                   134    76416940000128               None        39224
26                    94    83102491000109               None        86035
27                    12    49226780000181               None        83610
28                    26    80869886000143               None        85619
29                    90    78103884000105               None        39736
30                     1    04371703000187               None        92329
31                    15    95640520000175               None        42368
32                    21    27080563000193               None        75867
33                    54    50544220000154               None        83736
34                  3440    46374500000194               None        34952
35                    56    76205707000104               None        85074
36                    34    18133439000158               None        70391
37                   135    76416940000128               None        39224
38                    23    27080605000358               None        24367
39                    63    01266058000144               None        48356
40                    23    12517793000108               None         9974
41                    11    06272868000127               None        56302
42                    97    83009860000113               None        40264
43                  1836    96291141000180               None        42434
44                   741    13937032000160               None        12508
45                  1837    96291141000180               None        42434
46                    91    77816510000166               None        39701
47                    82    80257355000108               None        85580
48                  3441    46374500000194               None        34952
49                    22    04092672000125               None        52508

                             orgaoEntidadeRazaoSocial  \
0   SERVICO SOCIAL DO COMERCIO - ADMINISTRACAO REG...
1                 INSTITUTO NACIONAL DO SEGURO SOCIAL
2       AGENCIA ESTADUAL DE RECURSOS HIDRICOS - AGERH
3   AGENCIA MUNICIPAL DE REGULACAO DE SERVICOS DEL...
4                             MUNICIPIO DE RIO BRANCO
5                               MUNICIPIO DE SALVADOR
6   SECRETARIA DE ESTADO DA AGRICULTURA, ABASTECIM...
7                                MUNICIPIO DE CAETITE
8                      CAMARA MUNICIPAL DE MOGI GUACU
9                         MUNICIPIO DE BELO HORIZONTE
10                   MUNICIPIO DE CAJAZEIRAS DO PIAUI
11            MUNICIPIO DE NOVA ESPERANCA DO SUDOESTE
12                      SECRETARIA DE ESTADO DA SAUDE
13  EMPRESA DE INFORMATICA E INFORMACAO DO MUN.BHT...
14                               MUNICIPIO DE JUATUBA
15          SAO PAULO SECRETARIA DA SEGURANCA PUBLICA
16                             MUNICIPIO DE SCHROEDER
17  INSTITUTO DE ASSISTENCIA MEDICA AO SERVIDOR PU...
18        EMPRESA BRASILEIRA DE PESQUISA AGROPECUARIA
19                                MUNICIPIO DE MARIPA
20                                MUNICIPIO DE MARIPA
21  INSTITUTO DE ASSISTENCIA MEDICA AO SERVIDOR PU...
22                      SECRETARIA DE ESTADO DA SAUDE
23          SAO PAULO SECRETARIA DA SEGURANCA PUBLICA
24                               MUNICIPIO DE VARGEAO
25                                   ESTADO DO PARANA
26                             MUNICIPIO DE SCHROEDER
27                       SERTAOZINHO CAMARA MUNICIPAL
28                                MUNICIPIO DE SULINA
29                  MUNICIPIO DE NOVA PRATA DO IGUACU
30  DIRETORIA DE SAUDE DA POLICIA MILITAR DO ESPIR...
31                    MUNICIPIO DE BRASILANDIA DO SUL
32    ESPIRITO SANTO SECRETARIA DE ESTADO DA EDUCACAO
33                          CAMARA MUNICIPAL DE BAURU
34                      SECRETARIA DE ESTADO DA SAUDE
35                       MUNICIPIO DE SALTO DO LONTRA
36                         MUNICIPIO DE PEDRA DO ANTA
37                                   ESTADO DO PARANA
38                      SECRETARIA DE ESTADO DA SAUDE
39                               MUNICIPIO DE BURITIS
40  UNIVERSIDADE ESTADUAL DE CIENCIAS DA SAUDE DE ...
41           CONSELHO REGIONAL DE ENFERMAGEM COREN MA
42                               MUNICIPIO DE XANXERE
43  SAO PAULO SECRETARIA DA ADMINISTRACAO PENITENC...
44                                    ESTADO DA BAHIA
45  SAO PAULO SECRETARIA DA ADMINISTRACAO PENITENC...
46                     MUNICIPIO DE FRANCISCO BELTRAO
47              UNIVERSIDADE ESTADUAL DE PONTA GROSSA
48                      SECRETARIA DE ESTADO DA SAUDE
49                             MUNICIPIO DE JI-PARANA

   orgaoSubrogadoRazaoSocial orgaoEntidadeEsferaId  ...  \
0                       None                     N  ...
1                       None                     F  ...
2                       None                     E  ...
3                       None                     M  ...
4                       None                     M  ...
5                       None                     M  ...
6                       None                     E  ...
7                       None                     M  ...
8                       None                     M  ...
9                       None                     M  ...
10                      None                     M  ...
11                      None                     M  ...
12                      None                     E  ...
13                      None                     N  ...
14                      None                     M  ...
15                      None                     E  ...
16                      None                     M  ...
17                      None                     E  ...
18                      None                     F  ...
19                      None                     M  ...
20                      None                     M  ...
21                      None                     E  ...
22                      None                     E  ...
23                      None                     E  ...
24                      None                     M  ...
25                      None                     E  ...
26                      None                     M  ...
27                      None                     M  ...
28                      None                     M  ...
29                      None                     M  ...
30                      None                     E  ...
31                      None                     M  ...
32                      None                     E  ...
33                      None                     M  ...
34                      None                     E  ...
35                      None                     M  ...
36                      None                     M  ...
37                      None                     E  ...
38                      None                     E  ...
39                      None                     M  ...
40                      None                     E  ...
41                      None                     F  ...
42                      None                     M  ...
43                      None                     E  ...
44                      None                     E  ...
45                      None                     E  ...
46                      None                     M  ...
47                      None                     E  ...
48                      None                     E  ...
49                      None                     M  ...

   tipoInstrumentoConvocatorioNome modoDisputaNomePncp valorTotalEstimado  \
0                           Edital              Aberto          179474.46
1                           Edital              Aberto               0.00
2                           Edital              Aberto           10131.09
3                           Edital              Aberto         1885845.73
4                           Edital              Aberto           79607.20
5                           Edital              Aberto         1125246.12
6                           Edital              Aberto         5185454.82
7                           Edital              Aberto          423000.00
8                           Edital              Aberto          293237.06
9                           Edital      Aberto-Fechado         1198308.41
10                          Edital      Aberto-Fechado          189281.80
11                          Edital              Aberto           33916.85
12                          Edital              Aberto           91698.92
13                          Edital      Aberto-Fechado           56994.65
14                          Edital      Aberto-Fechado          637176.36
15                          Edital              Aberto           52245.06
16                          Edital              Aberto         1707137.60
17                          Edital      Aberto-Fechado          385875.75
18                          Edital              Aberto         2962694.77
19                          Edital              Aberto          356799.99
20                          Edital              Aberto           50397.00
21                          Edital      Aberto-Fechado          577107.45
22                          Edital      Aberto-Fechado          132000.00
23                          Edital              Aberto          725217.41
24                          Edital              Aberto           16945.00
25                          Edital              Aberto           18390.00
26                          Edital              Aberto          248021.25
27                          Edital      Aberto-Fechado          234933.77
28                          Edital              Aberto          133263.00
29                          Edital              Aberto           74199.90
30                          Edital      Aberto-Fechado          663523.87
31                          Edital              Aberto          200324.21
32                          Edital              Aberto         1174441.00
33                          Edital      Aberto-Fechado          148490.11
34                          Edital      Aberto-Fechado          420000.00
35                          Edital      Aberto-Fechado           92090.00
36                          Edital      Aberto-Fechado          128200.00
37                          Edital              Aberto         1035090.40
38                          Edital      Aberto-Fechado         2305710.86
39                          Edital              Aberto          417706.80
40                          Edital      Aberto-Fechado           25900.00
41                          Edital      Aberto-Fechado           81996.06
42                          Edital              Aberto          255277.50
43                          Edital              Aberto          639250.00
44                          Edital      Aberto-Fechado          176983.80
45                          Edital              Aberto          137759.53
46                          Edital      Aberto-Fechado          919513.15
47                          Edital              Aberto         1995761.30
48                          Edital              Aberto           13966.92
49                          Edital              Aberto          121880.00

   valorTotalHomologado     dataInclusaoPncp  dataAtualizacaoPncp  \
0          1.349944e+05  2025-05-02T07:15:29  2025-05-02T07:15:29
1                   NaN  2025-05-02T07:15:34  2025-05-02T07:15:34
2                   NaN  2025-05-02T07:15:38  2025-05-22T08:55:28
3          8.640561e+05  2025-05-02T07:15:42  2025-05-02T07:15:42
4          4.347620e+04  2025-05-02T07:15:46  2025-05-02T07:15:46
5          7.065490e+04  2025-05-02T07:15:50  2025-08-14T07:27:32
6          5.070000e+06  2025-05-02T07:15:54  2025-05-02T07:15:54
7                   NaN  2025-05-02T07:15:57  2025-05-02T07:15:57
8          2.880690e+05  2025-05-02T07:16:01  2025-05-02T07:16:01
9          8.911896e+05  2025-05-02T07:16:06  2025-05-02T07:16:06
10         1.487883e+05  2025-05-02T07:16:10  2025-05-02T07:16:10
11         3.367500e+04  2025-05-02T07:16:17  2025-05-02T07:16:17
12         7.525400e+03  2025-05-02T07:16:21  2025-05-02T07:16:21
13         4.354000e+04  2025-05-02T07:16:24  2025-05-19T12:32:56
14         1.201760e+05  2025-05-02T07:16:32  2025-05-14T08:28:28
15         4.400000e+04  2025-05-02T07:16:35  2025-05-02T07:16:35
16         1.071761e+06  2025-05-02T07:16:39  2025-05-02T07:16:39
17         1.743000e+05  2025-05-02T07:16:43  2025-05-02T07:16:43
18         1.756434e+06  2025-05-02T07:16:48  2025-05-02T07:16:48
19         4.050000e+04  2025-05-02T07:16:54  2025-05-02T07:16:54
20         4.074630e+04  2025-05-02T07:16:58  2025-05-02T07:16:58
21         2.757450e+05  2025-05-02T07:17:01  2025-05-02T07:17:01
22         1.320000e+05  2025-05-02T07:17:05  2025-05-02T07:17:05
23         7.225232e+05  2025-05-02T07:17:09  2025-05-14T08:20:52
24         1.079700e+04  2025-05-02T07:17:12  2025-05-02T07:17:12
25         1.722000e+04  2025-05-02T07:17:16  2025-05-02T07:17:16
26         2.104770e+05  2025-05-02T07:17:21  2025-05-02T07:17:21
27                  NaN  2025-05-02T07:17:25  2025-05-26T08:37:23
28         1.222000e+05  2025-05-02T07:17:29  2025-05-02T07:17:29
29         6.870000e+04  2025-05-02T07:17:33  2025-05-02T07:17:33
30         1.875000e+05  2025-05-02T07:17:36  2025-05-02T07:17:36
31         1.997000e+05  2025-05-02T07:17:40  2025-05-02T07:17:40
32                  NaN  2025-05-02T07:17:47  2025-06-05T08:17:22
33         1.079770e+05  2025-05-02T07:17:51  2025-05-02T07:17:51
34         2.730000e+05  2025-05-02T07:17:55  2025-05-02T07:17:55
35         7.049000e+04  2025-05-02T07:17:58  2025-05-02T07:17:58
36         9.199000e+04  2025-05-02T07:18:02  2025-05-02T07:18:02
37         8.787447e+05  2025-05-02T07:18:05  2025-05-02T07:18:05
38         1.416870e+06  2025-05-02T07:18:09  2025-05-02T07:18:09
39         3.490000e+05  2025-05-02T07:18:13  2025-06-04T08:01:28
40         2.590000e+04  2025-05-02T07:18:16  2025-05-02T07:18:16
41         3.151997e+04  2025-05-02T07:18:20  2025-05-02T07:18:20
42                  NaN  2025-05-02T07:18:23  2025-05-02T07:18:23
43         4.631470e+05  2025-05-02T07:18:27  2025-05-02T07:18:27
44         1.677088e+05  2025-05-02T07:18:34  2025-05-02T07:18:34
45         7.745611e+04  2025-05-02T07:18:38  2025-05-02T07:18:38
46         3.582080e+05  2025-05-02T07:18:43  2025-05-02T07:18:43
47         1.827400e+06  2025-05-02T07:18:48  2025-05-02T07:18:48
48         1.139520e+04  2025-05-02T07:18:51  2025-05-02T07:18:51

In [9]:
for i in registros:
    print(i)

{'idCompra': '92648305900402025', 'numeroControlePNCP': '03643856000173-1-000032/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 32, 'orgaoEntidadeCnpj': '03643856000173', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 97067, 'orgaoEntidadeRazaoSocial': 'SERVICO SOCIAL DO COMERCIO - ADMINISTRACAO REGIONAL NO ESTADO DE MINAS GERAIS', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'N', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926483', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SERVICO SOCIAL DO COMERCIO - SESC AR/MG', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'MG', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'BELO HORIZONTE', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3106200, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90040', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92648305900402025', 'processo': '004001-07686', 'objetoCompra': 'Contratação de empresa especializada para serviços de fornecimento e instalação de piso esportivo na quadra poliesportiva do ginásio e piso esportivo sport out na quadra poliesportiva externa da unidade Sesc Uberaba, incluindo toda mão de obra, equipamentos ferramentas e insumos para perfeita realização dos serviços a ser medido por preço unitário na virtude do não detalhamento de projeto.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 179474.46, 'valorTotalHomologado': 134994.42, 'dataInclusaoPncp': '2025-05-02T07:15:29', 'dataAtualizacaoPncp': '2025-05-02T07:15:29', 'dataPublicacaoPncp': '2025-05-02T07:15:29', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-16T09:00:00', 'contratacaoExcluida': False}
{'idCompra': '51018005900032025', 'numeroControlePNCP': '29979036000140-1-000100/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 100, 'orgaoEntidadeCnpj': '29979036000140', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 26661, 'orgaoEntidadeRazaoSocial': 'INSTITUTO NACIONAL DO SEGURO SOCIAL', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'F', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '510180', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SUPERINTENDENCIA REGIONAL SUDESTE II', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'MG', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'BELO HORIZONTE', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3106200, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90003', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=51018005900032025', 'processo': '35014096253202481', 'objetoCompra': 'Contratação de serviços terceirizados nas áreas administrativas para os postos de Assistente Administrativo, Recepcionista, Ascensorista, Copeiro, Carregador e Encarregado, a serem executados com regime de dedicação exclusiva de mão de obra, em diversos setores e unidades vinculados à Superintendência Regional Sudeste II', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 0.0, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:34', 'dataAtualizacaoPncp': '2025-05-02T07:15:34', 'dataPublicacaoPncp': '2025-05-02T07:15:34', 'dataAberturaPropostaPncp': '2025-05-02T09:00:00', 'dataEncerramentoPropostaPncp': '2025-05-21T10:00:00', 'contratacaoExcluida': False}
{'idCompra': '93008805900012025', 'numeroControlePNCP': '19481436000178-1-000006/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 6, 'orgaoEntidadeCnpj': '19481436000178', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 72415, 'orgaoEntidadeRazaoSocial': 'AGENCIA ESTADUAL DE RECURSOS HIDRICOS - AGERH', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'E', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '930088', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'EES - AGENCIA ESTADUAL DE RECURSOS HIDRICOS', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'ES', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'VITÓRIA', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3205309, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90001', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': False, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=93008805900012025', 'processo': '2024-5ZHFJ', 'objetoCompra': 'Contratação de Serviço de Copeiragem, Conservação e Manutenção Predial com fornecimento de equipamentos e ferramentas.', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 4, 'situacaoCompraNomePncp': 'Suspensa', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 10131.09, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:38', 'dataAtualizacaoPncp': '2025-05-22T08:55:28', 'dataPublicacaoPncp': '2025-05-02T07:15:38', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-21T10:00:00', 'contratacaoExcluida': False}
{'idCompra': '92670305900802025', 'numeroControlePNCP': '26981455000129-1-000078/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 78, 'orgaoEntidadeCnpj': '26981455000129', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 23517, 'orgaoEntidadeRazaoSocial': 'AGENCIA MUNICIPAL DE REGULACAO DE SERVICOS DELEGADOS- ARSER', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926703', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'AG. DE LICIT., CONT. E CONV. DE MACEIO', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'AL', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'MACEIÓ', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2704302, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90080', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'Em caso de divergência existente entre as especificações do objeto descritas no cadastro do Sistema COMPRASNET e as especificações constantes deste Edital e seus anexos, prevalecerão estas últimas. Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92670305900802025', 'processo': '12500.037111/2025', 'objetoCompra': 'Registro preços fornecimento utensílios e produtos de limpeza e higienização I (frac PE 90020/2025).', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 1885845.73, 'valorTotalHomologado': 864056.09, 'dataInclusaoPncp': '2025-05-02T07:15:42', 'dataAtualizacaoPncp': '2025-05-02T07:15:42', 'dataPublicacaoPncp': '2025-05-02T07:15:42', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-16T09:00:00', 'contratacaoExcluida': False}
{'idCompra': '98013905900422025', 'numeroControlePNCP': '04034583000122-1-000041/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 41, 'orgaoEntidadeCnpj': '04034583000122', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 52383, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE RIO BRANCO', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '980139', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'CAC-PREFEITURA MUNICIPAL DE RIO BRANCO', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'AC', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'RIO BRANCO', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 1200401, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90042', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'Havendo qualquer divergência entre as especificações do sistema e as do edital, prevalecerão as últimas. Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=98013905900422025', 'processo': '001/2025', 'objetoCompra': 'Aquisição de material de consumo de água mineral em garrafão de 20L, Gelo em barra, Água mineral em garrafa pet contendo 500ml, Água em copos pet contendo 300ml, Garrafão plástico 20L retornável, Botijão para gás vazio de 13kg, Gás liquefeito acondicionada em botijão de 13kg mediante a sistema de troca de botija, para atender as necessidades da Secretaria Municipal de Finanças - SEFIN, no município de Rio Branco/AC.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 79607.2, 'valorTotalHomologado': 43476.2, 'dataInclusaoPncp': '2025-05-02T07:15:46', 'dataAtualizacaoPncp': '2025-05-02T07:15:46', 'dataPublicacaoPncp': '2025-05-02T07:15:46', 'dataAberturaPropostaPncp': '2025-05-05T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-15T10:00:00', 'contratacaoExcluida': False}
{'idCompra': '92682105900502025', 'numeroControlePNCP': '13927801000300-1-000057/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 57, 'orgaoEntidadeCnpj': '13927801000300', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 65662, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE SALVADOR', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '926821', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'SECRETARIA MUNICIPAL DE GESTÃO SALVADOR - BA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'BA', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'SALVADOR', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2927408, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90050', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': 'As especificações devem ser seguidas conforme o edital Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92682105900502025', 'processo': '14679/2025', 'objetoCompra': 'Aquisição de MATERIAL DE PESTICIDAS – (INSETICIDA, LARVICIDA E RATICIDA) que tem por finalidade, atender as necessidades do funcionalismo da Administração da Prefeitura Municipal do Salvador, visando manter o pleno funcionamento das atividades, no suporte das tarefas e ações operacionais, através do sistema de registro de preços.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 1125246.12, 'valorTotalHomologado': 70654.9, 'dataInclusaoPncp': '2025-05-02T07:15:50', 'dataAtualizacaoPncp': '2025-08-14T07:27:32', 'dataPublicacaoPncp': '2025-05-02T07:15:50', 'dataAberturaPropostaPncp': '2025-08-14T08:00:00', 'dataEncerramentoPropostaPncp': '2025-09-03T14:00:00', 'contratacaoExcluida': False}
{'idCompra': '92573405900182025', 'numeroControlePNCP': '27080555000147-1-000028/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 28, 'orgaoEntidadeCnpj': '27080555000147', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 24356, 'orgaoEntidadeRazaoSocial': 'SECRETARIA DE ESTADO DA AGRICULTURA, ABASTECIMENTO, AQUICULTURA E PESCA - SEAG', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'E', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'E', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '925734', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'EES-SECRET. EST. AGR. ABAST. AQUIC. E PESCA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'ES', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'VITÓRIA', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 3205309, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90018', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=92573405900182025', 'processo': '2024-2X4Q7', 'objetoCompra': 'Registro de Preços para Aquisição de Secador Cilindrico Rotativo para Secagem de Grãos de Café com Capacidade mínima de 6.400 Litros, conforme descrito no Aexo I do Edital.', 'existeResultado': True, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 5185454.82, 'valorTotalHomologado': 5070000.0, 'dataInclusaoPncp': '2025-05-02T07:15:54', 'dataAtualizacaoPncp': '2025-05-02T07:15:54', 'dataPublicacaoPncp': '2025-05-02T07:15:54', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-15T10:00:00', 'contratacaoExcluida': False}
{'idCompra': '98340305900392025', 'numeroControlePNCP': '13811476000154-1-000108/2025', 'anoCompraPncp': 2025, 'sequencialCompraPncp': 108, 'orgaoEntidadeCnpj': '13811476000154', 'orgaoSubrogadoCnpj': None, 'codigoOrgao': 12165, 'orgaoEntidadeRazaoSocial': 'MUNICIPIO DE CAETITE', 'orgaoSubrogadoRazaoSocial': None, 'orgaoEntidadeEsferaId': 'M', 'orgaoSubrogadoEsferaId': None, 'orgaoEntidadePoderId': 'N', 'orgaoSubrogadoPoderId': None, 'unidadeOrgaoCodigoUnidade': '983403', 'unidadeSubrogadaCodigoUnidade': None, 'unidadeOrgaoNomeUnidade': 'PREFEITURA MUNICIPAL DE CAETITE - BA', 'unidadeSubrogadaNomeUnidade': None, 'unidadeOrgaoUfSigla': 'BA', 'unidadeSubrogadaUfSigla': None, 'unidadeOrgaoMunicipioNome': 'CAETITÉ', 'unidadeSubrogadaMunicipioNome': None, 'unidadeOrgaoCodigoIbge': 2905206, 'unidadeSubrogadaCodigoIbge': None, 'numeroCompra': '90039', 'modalidadeIdPncp': 6, 'codigoModalidade': 5, 'modalidadeNome': 'Pregão - Eletrônico', 'srp': True, 'modoDisputaIdPncp': 1, 'codigoModoDisputa': 1, 'amparoLegalCodigoPncp': 1, 'amparoLegalNome': 'Lei 14.133/2021, Art. 28, I', 'amparoLegalDescricao': 'pregão: modalidade de licitação obrigatória para aquisição de bens e serviços comuns', 'informacaoComplementar': ' Para as respostas de esclarecimentos e impugnações deste edital acesse o link: https://cnetmobile.estaleiro.serpro.gov.br/comprasnet-web/public/landing?destino=quadro-informativo&compra=98340305900392025', 'processo': '093/2025', 'objetoCompra': 'Registro de preços para futura e eventual aquisição de veículo utilitário, zero km, para atender as necessidades institucionais do Gabinete do Prefeito Municipal de Caetité-BA.', 'existeResultado': False, 'orcamentoSigilosoCodigo': 1, 'orcamentoSigilosoDescricao': 'Compra sem sigilo', 'situacaoCompraIdPncp': 1, 'situacaoCompraNomePncp': 'Divulgada no PNCP', 'tipoInstrumentoConvocatorioCodigoPncp': 1, 'tipoInstrumentoConvocatorioNome': 'Edital', 'modoDisputaNomePncp': 'Aberto', 'valorTotalEstimado': 423000.0, 'valorTotalHomologado': None, 'dataInclusaoPncp': '2025-05-02T07:15:57', 'dataAtualizacaoPncp': '2025-05-02T07:15:57', 'dataPublicacaoPncp': '2025-05-02T07:15:57', 'dataAberturaPropostaPncp': '2025-05-02T08:00:00', 'dataEncerramentoPropostaPncp': '2025-05-14T09:00:00', 'contratacaoExcluida': False}

In [17]:
import pandas as pd

# 1. Converte a sua variável 'registros' em um DataFrame do Pandas
df = pd.DataFrame(registros)

# Lista com as colunas essenciais para o seu tema
colunas_chave = [
    'srp',
    'numeroCompra',
    'orgaoEntidadeRazaoSocial',
    'modalidadeNome',
    'objetoCompra',
    'valorTotalEstimado',
    'valorTotalHomologado'
]

# Filtra apenas o subconjunto de colunas
df_resumido = df[colunas_chave]

# Separa com e sem SRP
df_com_srp = df_resumido[df_resumido['srp'] == 1]
df_sem_srp = df_resumido[df_resumido['srp'] == 0]

print("=== CONTRATAÇÕES COM SRP ===")
display(df_com_srp.head())

print("\n=== CONTRATAÇÕES SEM SRP ===")
display(df_sem_srp.head())

df_resumido.head(10)

=== CONTRATAÇÕES COM SRP ===

,srp,numeroCompra,orgaoEntidadeRazaoSocial,modalidadeNome,objetoCompra,valorTotalEstimado,valorTotalHomologado
3,True,90080,AGENCIA MUNICIPAL DE REGULACAO DE SERVICOS DEL...,Pregão - Eletrônico,Registro preços fornecimento utensílios e prod...,1885845.73,864056.09
4,True,90042,MUNICIPIO DE RIO BRANCO,Pregão - Eletrônico,Aquisição de material de consumo de água miner...,79607.20,43476.20
5,True,90050,MUNICIPIO DE SALVADOR,Pregão - Eletrônico,Aquisição de MATERIAL DE PESTICIDAS – (INSETIC...,1125246.12,70654.90
6,True,90018,"SECRETARIA DE ESTADO DA AGRICULTURA, ABASTECIM...",Pregão - Eletrônico,Registro de Preços para Aquisição de Secador C...,5185454.82,5070000.00
7,True,90039,MUNICIPIO DE CAETITE,Pregão - Eletrônico,Registro de preços para futura e eventual aqui...,423000.00,NaN

=== CONTRATAÇÕES SEM SRP ===

,srp,numeroCompra,orgaoEntidadeRazaoSocial,modalidadeNome,objetoCompra,valorTotalEstimado,valorTotalHomologado
0,False,90040,SERVICO SOCIAL DO COMERCIO - ADMINISTRACAO REG...,Pregão - Eletrônico,Contratação de empresa especializada para serv...,179474.46,134994.42
1,False,90003,INSTITUTO NACIONAL DO SEGURO SOCIAL,Pregão - Eletrônico,Contratação de serviços terceirizados nas área...,0.00,NaN
2,False,90001,AGENCIA ESTADUAL DE RECURSOS HIDRICOS - AGERH,Pregão - Eletrônico,"Contratação de Serviço de Copeiragem, Conserva...",10131.09,NaN
8,False,90001,CAMARA MUNICIPAL DE MOGI GUACU,Pregão - Eletrônico,Aquisição de microcomputadores para a Câmara M...,293237.06,288069.00
9,False,94142,MUNICIPIO DE BELO HORIZONTE,Pregão - Eletrônico,RP para aquisição de material médico hospitalar V,1198308.41,891189.61

,srp,numeroCompra,orgaoEntidadeRazaoSocial,modalidadeNome,objetoCompra,valorTotalEstimado,valorTotalHomologado
0,False,90040,SERVICO SOCIAL DO COMERCIO - ADMINISTRACAO REG...,Pregão - Eletrônico,Contratação de empresa especializada para serv...,179474.46,134994.42
1,False,90003,INSTITUTO NACIONAL DO SEGURO SOCIAL,Pregão - Eletrônico,Contratação de serviços terceirizados nas área...,0.00,NaN
2,False,90001,AGENCIA ESTADUAL DE RECURSOS HIDRICOS - AGERH,Pregão - Eletrônico,"Contratação de Serviço de Copeiragem, Conserva...",10131.09,NaN
3,True,90080,AGENCIA MUNICIPAL DE REGULACAO DE SERVICOS DEL...,Pregão - Eletrônico,Registro preços fornecimento utensílios e prod...,1885845.73,864056.09
4,True,90042,MUNICIPIO DE RIO BRANCO,Pregão - Eletrônico,Aquisição de material de consumo de água miner...,79607.20,43476.20
5,True,90050,MUNICIPIO DE SALVADOR,Pregão - Eletrônico,Aquisição de MATERIAL DE PESTICIDAS – (INSETIC...,1125246.12,70654.90
6,True,90018,"SECRETARIA DE ESTADO DA AGRICULTURA, ABASTECIM...",Pregão - Eletrônico,Registro de Preços para Aquisição de Secador C...,5185454.82,5070000.00
7,True,90039,MUNICIPIO DE CAETITE,Pregão - Eletrônico,Registro de preços para futura e eventual aqui...,423000.00,NaN
8,False,90001,CAMARA MUNICIPAL DE MOGI GUACU,Pregão - Eletrônico,Aquisição de microcomputadores para a Câmara M...,293237.06,288069.00
9,False,94142,MUNICIPIO DE BELO HORIZONTE,Pregão - Eletrônico,RP para aquisição de material médico hospitalar V,1198308.41,891189.61